import './globals.css';
import { Inter } from 'next/font/google';
import Header from './header';
import Bottom from './bottom';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Header />
        {children}
        <Bottom />
      </body>
    </html>
  );
}
